version: "3.8"

services:
  auth-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auth-server
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES=3600s

  event-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: event-server
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES=3600s

  gateway-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: gateway-server
    ports:
      - "3000:3000"
    depends_on:
      - auth-server
      - event-server
    environment:
      - MONGO_URI=mongodb://mongodb:27017/db
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES=3600s

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
