version: "3.8"

services:
  auth-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auth-server
    ports:
      - "3001:3000"
    depends_on:
      - mongo

  event-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: event-server
    ports:
      - "3002:3000"
    depends_on:
      - mongo

  gateway-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: gateway-server
    ports:
      - "3000:3000"
    depends_on:
      - auth-server
      - event-server

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
